import { DialogProvider } from "@/components/ui/modifiedcn/dialogContext";
import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Alsun App",
  description: "Generated by Create Alsun App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr" className="scroll-smooth">
      <body className="font-alsun-sans relative min-h-screen bg-slate-100 text-secondary">
        <div className="bg-secondary absolute inset-0 -z-10 size-full mask-[url()] opacity-7" />
        <DialogProvider>{children}</DialogProvider>
        <noscript className="">
          <div className="absolute inset-0">
            <div className="sticky inset-0 w-full h-screen flex items-center justify-center bg-black/70 z-99">
              <div className="bg-red-600/30 backdrop-blur-lg p-6 rounded-3xl text-white uppercase tracking-widest z-100 shadow-2xl shadow-black">
                This site needs JavaScript enabled.
              </div>
            </div>
          </div>
        </noscript>
        <Toaster position="bottom-center" />
      </body>
    </html>
  );
}
